version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: jdbc-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jdbc.db
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"